### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by mirek** [beaufour/mtop#17]
```
Ops: 1645 total,   54 getmore,   56 insert, 1444 update,   90 command,    1 query,    0 delete
         ID                CLIENT      OP A LOCKW NS / QUERY

Traceback (most recent call last):
  File "./.local/bin/mtop", line 9, in <module>
    load_entry_point('mtop==0.5', 'console_scripts', 'mtop')()
  File "/home/mirek/.local/lib/python2.7/site-packages/mtop-0.5-py2.7.egg/mtop/main.py", line 42, in main
    rc = runner.run()
  File "/home/mirek/.local/lib/python2.7/site-packages/mtop-0.5-py2.7.egg/mtop/lib/runner.py", line 36, in run
    return self._do_run()
  File "/home/mirek/.local/lib/python2.7/site-packages/mtop-0.5-py2.7.egg/mtop/lib/runner.py", line 67, in _do_run
    self._inprog(inprog)
  File "/home/mirek/.local/lib/python2.7/site-packages/mtop-0.5-py2.7.egg/mtop/lib/runner.py", line 152, in _inprog
    ns_query += " " + json.dumps(stringify_query_dict(query))[:(self._maxx - 40)]
  File "/home/mirek/.local/lib/python2.7/site-packages/mtop-0.5-py2.7.egg/mtop/lib/util.py", line 52, in stringify_query_dict
    elif is_string(v, str):
TypeError: is_string() takes exactly 1 argument (2 given)
```

**Comment by beaufour** [comment]
Bah, sorry I fixed that a while ago but apparently forgot to push a new version. Upgrade to v0.6 and it is fixed.
